#!/bin/bash

############################################################################
#
# Copyright (c) 2013 - Based on Kyle Frost (frostincredible@gmail.com)
#                        Moded by ptichalouf
# This setup script is 100% free.  This script file is intended for personal
# and/or educational use only.         It may not be duplicated for monetary
# benefit  or  any other purpose  without  the permission  of the developer.
#
############################################################################


version=1

chmod 777 scripts/*
chmod 777 scripts/advanced_scripts/*
chmod 777 scripts/advanced_scripts/initialize_aokp_repo/*
chmod 777 scripts/advanced_scripts/initialize_cm_repo/*
chmod 777 scripts/advanced_scripts/initialize_liquid_repo/*
chmod 777 scripts/advanced_scripts/initialize_omni_repo/*
chmod 777 scripts/dmg_sizes/*
chmod 777 scripts/folder_names/*

while :
do

  clear

  echo
  echo "============================================================"
  echo "        Linux Build Set Up $version - based on Kyle Frost"
  echo "                  By ptichalouf@gmail.com "
  echo "============================================================"
  echo
  echo "                     ---Main Menu---"
  echo
  echo "  1 - Install required files"
  echo
  echo "  2 - Initialize Repo"
  echo
  echo "  3 - Build ROM"
  echo
  echo "  x - Exit"
  echo
  echo -n "Enter option: "
  read opt

  if [ "$?" != "1" ]
  then
    case $opt in
      1) scripts/install_files; continue;; 
      2) scripts/initialize; continue;;
      3) scripts/build; continue;;
      x) scripts/dummy_script; clear; echo; echo "Goodbye."; echo; exit 1;;
      *) echo "Invalid option"; continue;;
    esac
  fi

  scripts/press_enter

done

