#!/bin/bash

############################################################################
#
# Copyright (c) 2013 - Kyle Frost (frostincredible@gmail.com)
#        Mod by ( ptichalouf@gmail.com)
# This setup script is 100% free.  This script file is intended for personal
# and/or educational use only.         It may not be duplicated for monetary
# benefit  or  any other purpose  without  the permission  of the developer.
#
############################################################################

sudo apt-get install git-core gnupg flex bison gperf build-essential zip curl libc6-dev libncurses5-dev:i386 x11proto-core-dev libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-glx:i386 libgl1-mesa-dev g++-multilib mingw32 openjdk-6-jdk tofrodos python-markdown schedtool pngcrush libxml2-utils xsltproc zlib1g-dev:i386

sudo ln -s /usr/lib/i386-linux-gnu/mesa/libGL.so.1 /usr/lib/i386-linux-gnu/libGL.so

mkdir ~/bin

PATH=~/bin:$PATH

curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo

chmod a+x ~/bin/repo

mkdir ~/*YOUR_REPO*

#Exemple mkdir~/aokp
#Exemple mkdir~/carbon

cd ~/*YOUR_REPO*

#Exemple cd~/aokp
#Exemple cd~/carbon


